function  label2=prompt2(combined)
label2  = zeros(length(combined) * 20,1) ;
prompt2 = ['假如你是一名研究银行金融科技创新的学术领域专家，银行的20个专利文本，' ...
    '现假设将银行金融科技创新策略分为稳健创新与激进创新。其中，' ...
    '稳健创新指商业银行在合规和风险可控前提下，通过技术或模式优化推动创新，合理运用人工智能、' ...
    '云计算等科技手段拓展业务，提高银行内部运行效率和管理能力，' ...
    '注重在现有规则和风险容忍度内逐步推进创新，避免对银行经营稳定性产生剧烈冲击；' ...
    '激进创新则指商业银行出于获取超额收益的动机，' ...
    '以科技手段为加持在业务选择上转向并不熟悉的高风险业务或新型的金融产品，' ...
    '忽视潜在风险或监管边界。此外，可考虑激进创新的特征包括：1.创新内容是否太特立独行；' ...
    '2.技术是否不成熟、市场接受度低、监管政策不确定；3.是否试图突破传统业务瓶颈；' ...
    '4.是否实施过程可能较为迅速，需要在短时间内集中资源进行研发和推广。请分析其内容后，' ...
    '判断专利的激进程度，在1-5的区间内进行整数值的打分，形成表格，第一列为专利序号，' ...
    '第二列为分数，第三列为简要的理由，注意分数需要有一定的区分性。'];%激进程度
totaltime = 0;
for j = 1:size(combined, 1)
    tic;
    prompt2      = combined{j} + newline + prompt2;
    %scores       = randi([1, 5], 20, 1);%测试
    response     = call_deepseek_api(1, prompt2);
    scores       = regexp(response, '\|\s*\d+\s*\|\s*(\d+)\s*\|', 'tokens');
    scores       = str2double([scores{:}])';
    for i = 1:20
        rowidx           = (j - 1)*20 + i ;
        label2(rowidx,1) = scores(i) ;
    end
    singleime  = toc;
    totaltime  = totaltime + singleime;
    fprintf('第 %d 次，总共 %d 次\n', j, size(combined, 1));
    fprintf('单次用时: %.4f 秒\n'   , singleime);
    fprintf('累计用时: %.4f 秒\n'   , totaltime);
end
